version: "2.0"
type: node-port
services:
  vm:
    image: filswan/ubuntu-ssh-user:22.04
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEl6cawQj9pHsoUVz4Dd1kyL0X289MdIXCq5UVQQUiuN/nI3GauOniodNH67s2cMVzA06tR6Sx6/sKxEukOq5mq7ikTLioH0ualPoaggMA5Z7LON6KmhUmT7DEy64oaTBmzh4lQjnIY7r3Fg2w0ifEQ8V0OPlGu3tySmT1y/OzwTOhag1WSi2+DDXhQWLzGFYxTfbGZvz2ktpik+UabL2wmm/iZvnkb4p1KWXq2pD8dmDlkrEs95SYUdbTN9g97FBr6/1BYen7BxRUoTVGRcBQ3Bx4N05j89vgTj9tcZq8pJNTv3YlDpdLIUX+7Hh55skFnB0ADkMdqcCA+QjDArwm9DIzolHP8hPDpeqlZ/9p6wUB0344xly3H95onTfFC4yCwQmdFFKqM5oHR1TI4L661H74RR4zOGb7/JkcQloA9Tppnd+gw2bkkE51ivLljZh7UVakyA7ng0V7MDVdk+q1bJVwXzU1hcrOs4t9m4G10TfQYhifq9mLegAPWTouK91MCmvXM4RVB0xM2kHWHr/Izi3CNl9lu8Z4gQdx621ptbuLfaQuk8ocXN9JJ6LoQrEq3BD1RQAmDZVJGeRbUM0dUdIP0YXVLKzm5DQ8PHoEku8uK0sQ4+x365yi29LwdFzjjM6sBXhjCaL5dFShGZhuLLYTjK7SOZbbGQfXpa/44Q== aaronli@Mac.lan
      - username=swantouser
    expose:
        - port: 22
        - port: 30002
        - port: 30003
        - port: 30004
        - port: 30005
        - port: 30006
        - port: 30007
deployment:
  vm:
    lagrange:
      count: 1
